USE INVENTARIO;

CREATE TABLE TIPOS_MUSICA(
ID_TIPO INT,
NOMBRE_TIPO VARCHAR(20) NOT NULL,
constraint UN_NOMBRE_TIPO UNIQUE(NOMBRE_TIPO),
CONSTRAINT PK_TIPOS_MUSICA PRIMARY KEY(ID_TIPO)
);

CREATE TABLE DISQUERAS_CD( 
ID_DISQUERA INT,
NOMBRE_COMPAÑIA VARCHAR(20) default "INDEPENDIENTE" NOT NULL,
CONSTRAINT PK_DISQUERAS_CD PRIMARY KEY (ID_DISQUERA)
);

CREATE TABLE DISCOS_COMPACTOS(
ID_DISCO_COMPACTO INT,
TITULO_CD VARCHAR(20) NOT NULL,
ID_DISQUERA INT NOT NULL,
CONSTRAINT PK_DISCOS_COMPACTOS PRIMARY KEY(ID_DISCO_COMPACTO),
CONSTRAINT FK_ID_DISQUERA FOREIGN KEY (ID_DISQUERA) REFERENCES 
DISQUERAS_CD(ID_DISQUERA) -- SE TIENE QUE PONER ASPI
);

CREATE TABLE TIPOS_DISCO_COMPACTO(
ID_DISCO_COMPACTO INT,
ID_TIPO_MUSICA INT,
CONSTRAINT PK_TIPOS_DISCO_COMPACTO PRIMARY KEY (ID_DISCO_COMPACTO,ID_TIPO_MUSICA),
CONSTRAINT FK_ID_DISCOS_COMPACTOS_01 FOREIGN KEY (ID_DISCO_COMPACTO) REFERENCES DISCOS_COMPACTOS(ID_DISCO_COMPACTO),
CONSTRAINT FK_ID_TIPO_MUSICA FOREIGN KEY (ID_TIPO_MUSICA) REFERENCES TIPOS_MUSICA(ID_TIPO)
);

CREATE TABLE ARTISTAS(
ID_ARTISTA INT,
NOMBRE_ARTISTA VARCHAR(20) NOT NULL,
LUGAR_DE_NACIMIENTO VARCHAR(60) DEFAULT 'DESCONOCIDO' NOT NULL,
CONSTRAINT PK_ARTISTAS PRIMARY KEY (ID_ARTISTA)
);

CREATE TABLE CDS_ARTISTAS(
ID_ARTISTA INT,
ID_DISCO_COMPACTO INT,
CONSTRAINT PK_CDS_ARTISTA primary key (ID_ARTISTA,ID_DISCO_COMPACTO),
CONSTRAINT FK_ID_ARTISTA FOREIGN KEY (ID_ARTISTA) REFERENCES ARTISTAS(ID_ARTISTA),
CONSTRAINT FK_ID_DISCOS_COMPACTOS_02 FOREIGN KEY (ID_DISCO_COMPACTO) REFERENCES DISCOS_COMPACTOS(ID_DISCO_COMPACTO)
);


-- 4-2
ALTER TABLE DISCOS_COMPACTOS
ADD COLUMN EN_EXISTENCIA INT NOT NULL;
select * from DISCOS_COMPACTOS;

ALTER TABLE DISCOS_COMPACTOS
ADD CONSTRAINT ck_EN_EXISTENCIA CHECK (
EN_EXISTENCIA > 0 AND EN_EXISTENCIA <50
); -- SE AGRE LA RESTRICCION QUE HACE QUE LOS  REGISTROS TENGAN VALORES DENTRO DE ESTE RANGO PARA EL CAMPO "EN_EXISTENCIA"


-- 5 
CREATE TABLE INVENTARIO_DISCO_COMPACTO( 
ID_DISCO_COMPACTO INT, TITULO_CD VARCHAR(60), COPYRIGHT INT, ID_DISQUERA INT, ID_DISCO INT, EN_EXISTENCIA INT
);

ALTER TABLE INVENTARIO_DISCO_COMPACTO
ADD CONSTRAINT PRIMARY KEY (ID_DISCO_COMPACTO);

SELECT * FROM INVENTARIO_DISCO_COMPACTO;

CREATE VIEW DISCOS_COMPACTOS_EN_EXISTENCIA -- SE CREA LA VISTA DE LA TABLA ANTERIOR
( DISCO_COMPACTO, DERECHOSDEAUTOR, EN_EXISTENCIA ) AS
SELECT ID_DISCO_COMPACTO,COPYRIGHT,EN_EXISTENCIA FROM INVENTARIO_DISCO_COMPACTO
;

SELECT * FROM DISCOS_COMPACTOS_EN_EXISTENCIA;

CREATE VIEW CDS_EN_EXISTENCIA_1990S
( DISCO_COMPACTO, DERECHOSDEAUTOR, EN_EXISTENCIA ) AS
SELECT ID_DISCO_COMPACTO,COPYRIGHT,EN_EXISTENCIA FROM INVENTARIO_DISCO_COMPACTO
WHERE COPYRIGHT>1989 AND COPYRIGHT<2000;

SELECT * FROM CDS_EN_EXISTENCIA_1990S;

CREATE TABLE INVENTARIO_CD(
ID_DISCO_COMPACTO INT, TITULO_CD VARCHAR(60), ID_DISQUERA INT
);
SELECT * FROM INVENTARIO_CD;

CREATE TABLE DISQUERAS(
ID_DISQUERA INT, NOMBRE_COMPAÑIA VARCHAR(60)
);
SELECT * FROM DISQUERAS;

-- En esta  VIEW se unen las dos  tablas anteriores

CREATE VIEW EDITORES_DISCO_COMPACTO
 ( DISCO_COMPACTO, EDITOR ) AS
 SELECT INVENTARIO_CD.TITULO_CD, DISQUERAS.NOMBRE_COMPAÑIA
 FROM INVENTARIO_CD,DISQUERAS 
 WHERE INVENTARIO_CD.ID_DISQUERA = DISQUERAS.ID_DISQUERA
;
SELECT * FROM EDITORES_DISCO_COMPACTO;


CREATE TABLE INVENTARIO(
ID_DISCO_COMPACTO INT, TITULO_CD VARCHAR(60), COPYRIGHT INT, PRECIO_MENUDEO NUMERIC(5,2),EN_EXISTENCIA INT
);

SELECT * FROM INVENTARIO;

CREATE VIEW DESCUENTOS_CD
(DISCO_COMPACTO,PRECIO_MENUDEO,PRECIO_DESCUENTO) AS
SELECT TITULO_CD,PRECIO_MENUDEO,PRECIO_MENUDEO*0.9 
FROM INVENTARIO ; -- PRECIO_MENUDEO SE MULTIPPLICA POR 0.9 PUES TIENE UN DESCUENTO DEL 10 %

SELECT * FROM DESCUENTOS_CD;

--   VIEWS actualizables

CREATE TABLE COMISIONES_EMPLEADO(
ID_EMPLEADO INT, AÑO_1999 NUMERIC(7,2),AÑO_2000 NUMERIC(7,2),AÑO_2001 NUMERIC(7,2)
);

SELECT * FROM COMISIONES_EMPLEADO;

CREATE VIEW COM_EMP_PROMS
(PROM_1999,PROM_2000,PROM_2001) AS
SELECT AVG(AÑO_1999), AVG(AÑO_2000),AVG(AÑO_2001) -- CALCULA EL PROMEDIO DE LAS COLUMNAS  
FROM COMISIONES_EMPLEADO;

SELECT * FROM COM_EMP_PROMS;

CREATE VIEW COM_EMP_PROMS
(ID_EMPLEADO,PROM_1999,PROM_2000) AS
SELECT ID_EMPLEADO, AÑO_1999,AÑO_1999 -- CALCULA EL PROMEDIO DE LAS COLUMNAS  
FROM COMISIONES_EMPLEADO
WHERE AÑO_1999>100
WITH CHECK OPTION ; -- ESTO HACE QUE LA VISTA NO SE PUEDE ACTUALIZAR SI SE VIOLA LA CONDOCIÓN DEL WHERE

select * from DISCOS_COMPACTOS;

-- 5-1
CREATE VIEW CD_EN_EXISTENCIA AS
SELECT TITULO_CD,EN_EXISTENCIA FROM DISCOS_COMPACTOS
WHERE EN_EXISTENCIA>10
WITH CHECK option;

SELECT * FROM CD_EN_EXISTENCIA;

CREATE VIEW EDITORES_CD AS
SELECT DISCOS_COMPACTOS.TITULO_CD, DISQUERAS_CD.NOMBRE_COMPAÑIA
FROM DISCOS_COMPACTOS, DISQUERAS_CD
WHERE DISCOS_COMPACTOS.ID_DISQUERA =DISQUERAS_CD.ID_DISQUERA;

SELECT * FROM EDITORES_CD;
