
-- FUNCIO PARA ESCOGER ENTRE EL PRECIO VENTA O EL DE PROMOCION
DELIMITER //

CREATE FUNCTION PRECIO ( PRECIO_REAL INT, PRECIO_PROMO INT )
RETURNS INT
READS SQL DATA
DETERMINISTIC
BEGIN
   DECLARE PRECIO int;
   
   IF PRECIO_REAL !=0 THEN
      SET PRECIO = PRECIO_REAL;
   ELSE
      SET PRECIO = PRECIO_PROMO;
   END IF;

   RETURN PRECIO;
END; // 
DELIMITER ;
