CREATE SCHEMA IF NOT EXISTS   DOMO;

USE DOMO;

CREATE TABLE IF NOT EXISTS mae_ordenes(
sec_ordencommerce VARCHAR(100),
sec_orden VARCHAR(100),
fec_fechaorden VARCHAR(100),
sec_nota VARCHAR(100),
sec_factura VARCHAR(100),
idu_clientecodigo VARCHAR(100),
nom_cliente VARCHAR(100),
nom_apellidopaterno VARCHAR(100),
nom_apellidomaterno VARCHAR(100),
des_correoelectronico VARCHAR(100),
num_telefono VARCHAR(100),
opc_celular VARCHAR(100),
nom_completorecibe VARCHAR(200),
idu_estadocodigo INT,
idu_MapaDomoCodigo INT,
nom_estado VARCHAR(100),
idu_ciudadcodigo INT,
nom_ciudad VARCHAR(200),
idu_coloniacodigo INT,
nom_colonia VARCHAR(200),
nom_calle VARCHAR(200),
nom_entrecalles VARCHAR(200),
num_casa INT,
num_interior VARCHAR(100),
num_exterior INT,
num_codigopostal INT,
des_observaciones VARCHAR(500),
idu_articulocodigo VARCHAR(200),
num_cantidad INT,
imp_preciounitario NUMERIC(8,2),
imp_preciocreditounitario  NUMERIC(8,2),
idu_articuloproductocommercecodigo VARCHAR(100),
idu_articuloitemcommercecodigo VARCHAR(100),
idu_tipopagocodigo INT,
des_tipopago VARCHAR(200),
des_tipocompra VARCHAR(200),
des_pagoinicial VARCHAR(200),
des_formapago VARCHAR(200),
des_tipopagogrupo VARCHAR(200),
des_tipopagogrupo2 VARCHAR(200),
des_tipopagogrupo3 VARCHAR(200),
idu_estatuspedidocodigo INT,
des_estatusorden VARCHAR(200),
idu_codigobanco INT,
des_establecimientobanco VARCHAR(200),
num_referencia VARCHAR(200),
fec_FechaFacturacion VARCHAR(100),
idu_areacodigo INT,
des_Area VARCHAR(100),
idu_departamentocodigo INT,
des_departamento VARCHAR(100),
idu_clasecodigo VARCHAR(100),
des_clase VARCHAR(200),
idu_familiacodigo INT,
des_familia VARCHAR(200),
des_categoria VARCHAR(200),
des_subcategoria VARCHAR(100),
des_clasificacionantad VARCHAR(100),
des_articulo VARCHAR(100),
num_talla VARCHAR(100),
des_modelo VARCHAR(100),
des_color VARCHAR(100),
des_marca VARCHAR(100),
des_EstatusAccertify VARCHAR(100),
fec_fechaordencommerce VARCHAR(100),
des_BuildingBlock VARCHAR(100),
des_buildingblockagg VARCHAR(100),
des_Fuente VARCHAR(100),
des_Medio VARCHAR(100),
des_campagna VARCHAR(200),
des_Dispositivo VARCHAR(100),
idu_TiendaCodigoR VARCHAR(100),
nom_NombreTiendaR VARCHAR(100),
idu_FormatoTiendaCodigoR VARCHAR(100),
des_FormatoTiendaR VARCHAR(200),
idu_CiudadTiendaCodigoR VARCHAR(200),
nom_NombreCiudadR VARCHAR(200),
flag_ventafuturo VARCHAR(50),
num_tiendaCT VARCHAR(200),
des_FormatoCT VARCHAR(200),
flag_logeado INT
);

-- drop table mae_ordenes;

-- 4) cargar los datos
LOAD DATA INFILE '/var/lib/mysql-files/mae_ordenes.csv'
into table mae_ordenes
FIELDS TERMINATED BY '|'
ENCLOSED BY ''
LINES terminated by '\n'
IGNORE 1 ROWS

(@sec_ordencommerce,
@sec_orden,
@fec_fechaorden,
@sec_nota,
@sec_factura,
@idu_clientecodigo,
@nom_cliente,
@nom_apellidopaterno,
@nom_apellidomaterno,
@des_correoelectronico,
@num_telefono,
@opc_celular,
@nom_completorecibe,
@idu_estadocodigo,
@idu_MapaDomoCodigo,
@nom_estado,
@idu_ciudadcodigo,
@nom_ciudad,
@idu_coloniacodigo,
@nom_colonia,
@nom_calle,
@nom_entrecalles,
@num_casa,
@num_interior,
@num_exterior,
@num_codigopostal,
@des_observaciones,
@idu_articulocodigo,
@num_cantidad,
@imp_preciounitario,
@imp_preciocreditounitario,
@idu_articuloproductocommercecodigo,
@idu_articuloitemcommercecodigo,
@idu_tipopagocodigo,
@des_tipopago,
@des_tipocompra,
@des_pagoinicial,
@des_formapago,
@des_tipopagogrupo,
@des_tipopagogrupo2,
@des_tipopagogrupo3,
@idu_estatuspedidocodigo,
@des_estatusorden,
@idu_codigobanco,
@des_establecimientobanco,
@num_referencia,
@fec_FechaFacturacion,
@idu_areacodigo,
@des_Area,
@idu_departamentocodigo,
@des_departamento,
@idu_clasecodigo,
@des_clase,
@idu_familiacodigo,
@des_familia,
@des_categoria,
@des_subcategoria,
@des_clasificacionantad,
@des_articulo,
@num_talla,
@des_modelo,
@des_color,
@des_marca,
@des_EstatusAccertify,
@fec_fechaordencommerce,
@des_BuildingBlock,
@des_buildingblockagg,
@des_Fuente,
@des_Medio,
@des_campagna,
@des_Dispositivo,
@idu_TiendaCodigoR,
@nom_NombreTiendaR,
@idu_FormatoTiendaCodigoR,
@des_FormatoTiendaR,
@idu_CiudadTiendaCodigoR,
@nom_NombreCiudadR,
@flag_ventafuturo,
@num_tiendaCT,
@des_FormatoCT,
@flag_logeado)

SET 

sec_ordencommerce= NULLIF(@sec_ordencommerce,'NULL'),
sec_orden= NULLIF(@sec_orden,'NULL'),
fec_fechaorden= NULLIF(@fec_fechaorden,'NULL'),
idu_clientecodigo= NULLIF(@idu_clientecodigo,'NULL'),
nom_cliente= NULLIF(@nom_cliente,'NULL'),
nom_apellidopaterno= NULLIF(@nom_apellidopaterno,'NULL'),
nom_apellidomaterno= NULLIF(@nom_apellidomaterno,'NULL'),
des_correoelectronico= NULLIF(@des_correoelectronico,'NULL'),
num_telefono= NULLIF(@num_telefono,'NULL'),
opc_celular= NULLIF(@opc_celular,'NULL'),
nom_completorecibe= NULLIF(@nom_completorecibe,'NULL'),
idu_estadocodigo= NULLIF(@idu_estadocodigo,'NULL'),
idu_MapaDomoCodigo= NULLIF(@idu_MapaDomoCodigo,'NULL'),
nom_estado= NULLIF(@nom_estado,'NULL'),
idu_ciudadcodigo= NULLIF(@idu_ciudadcodigo,'NULL'),
nom_ciudad= NULLIF(@nom_ciudad,'NULL'),
idu_coloniacodigo= NULLIF(@idu_coloniacodigo,'NULL'),
nom_colonia= NULLIF(@nom_colonia,'NULL'),
nom_calle= NULLIF(@nom_calle,'NULL'),
nom_entrecalles= NULLIF(@nom_entrecalles,'NULL'),
num_casa= NULLIF(@num_casa,'NULL'),
num_interior= NULLIF(@num_interior,'NULL'),
num_exterior= NULLIF(@num_exterior,'NULL'),
num_codigopostal= NULLIF(@num_codigopostal,'NULL'),
des_observaciones= NULLIF(@des_observaciones,'NULL'),
idu_articulocodigo= NULLIF(@idu_articulocodigo,'NULL'),
num_cantidad= NULLIF(@num_cantidad,'NULL'),
imp_preciounitario= NULLIF(@imp_preciounitario,'NULL'),
imp_preciocreditounitario= NULLIF(@imp_preciocreditounitario,'NULL'),
idu_articuloproductocommercecodigo= NULLIF(@idu_articuloproductocommercecodigo,'NULL'),
idu_articuloitemcommercecodigo= NULLIF(@idu_articuloitemcommercecodigo,'NULL'),
idu_tipopagocodigo= NULLIF(@idu_tipopagocodigo,'NULL'),
des_tipopago= NULLIF(@des_tipopago,'NULL'),
des_tipocompra= NULLIF(@des_tipocompra,'NULL'),
des_pagoinicial= NULLIF(@des_pagoinicial,'NULL'),
des_formapago= NULLIF(@des_formapago,'NULL'),
des_tipopagogrupo= NULLIF(@des_tipopagogrupo,'NULL'),
des_tipopagogrupo2= NULLIF(@des_tipopagogrupo2,'NULL'),
des_tipopagogrupo3= NULLIF(@des_tipopagogrupo3,'NULL'),
idu_estatuspedidocodigo= NULLIF(@idu_estatuspedidocodigo,'NULL'),
des_estatusorden= NULLIF(@des_estatusorden,'NULL'),
idu_codigobanco= NULLIF(@idu_codigobanco,'NULL'),
des_establecimientobanco= NULLIF(@des_establecimientobanco,'NULL'),
num_referencia= NULLIF(@num_referencia,'NULL'),
fec_FechaFacturacion= NULLIF(@fec_FechaFacturacion,'NULL'),
idu_areacodigo= NULLIF(@idu_areacodigo,'NULL'),
des_Area= NULLIF(@des_Area,'NULL'),
idu_departamentocodigo= NULLIF(@idu_departamentocodigo,'NULL'),
des_departamento= NULLIF(@des_departamento,'NULL'),
idu_clasecodigo= NULLIF(@idu_clasecodigo,'NULL'),
des_clase= NULLIF(@des_clase,'NULL'),
idu_familiacodigo= NULLIF(@idu_familiacodigo,'NULL'),
des_familia= NULLIF(@des_familia,'NULL'),
des_categoria= NULLIF(@des_categoria,'NULL'),
des_subcategoria= NULLIF(@des_subcategoria,'NULL'),
des_clasificacionantad= NULLIF(@des_clasificacionantad,'NULL'),
des_articulo= NULLIF(@des_articulo,'NULL'),
num_talla= NULLIF(@num_talla,'NULL'),
des_modelo= NULLIF(@des_modelo,'NULL'),
des_color= NULLIF(@des_color,'NULL'),
des_marca= NULLIF(@des_marca,'NULL'),
des_EstatusAccertify= NULLIF(@des_EstatusAccertify,'NULL'),
fec_fechaordencommerce= NULLIF(@fec_fechaordencommerce,'NULL'),
des_BuildingBlock= NULLIF(@des_BuildingBlock,'NULL'),
des_buildingblockagg= NULLIF(@des_buildingblockagg,'NULL'),
des_Fuente= NULLIF(@des_Fuente,'NULL'),
des_Medio= NULLIF(@des_Medio,'NULL'),
des_campagna= NULLIF(@des_campagna,'NULL'),
des_Dispositivo= NULLIF(@des_Dispositivo,'NULL'),
idu_TiendaCodigoR= NULLIF(@idu_TiendaCodigoR,'NULL'),
nom_NombreTiendaR= NULLIF(@nom_NombreTiendaR,'NULL'),
idu_FormatoTiendaCodigoR= NULLIF(@idu_FormatoTiendaCodigoR,'NULL'),
des_FormatoTiendaR= NULLIF(@des_FormatoTiendaR,'NULL'),
idu_CiudadTiendaCodigoR= NULLIF(@idu_CiudadTiendaCodigoR,'NULL'),
nom_NombreCiudadR= NULLIF(@nom_NombreCiudadR,'NULL'),
flag_ventafuturo= NULLIF(@flag_ventafuturo,'NULL'),
num_tiendaCT= NULLIF(@num_tiendaCT,'NULL'),
des_FormatoCT= NULLIF(@des_FormatoCT,'NULL'),
flag_logeado= NULLIF(@flag_logeado,'NULL');

select  * from mae_ordenes LIMIT 10; 

-- ALTER TABLE mae_ordenes RENAME COLUMN ﻿sec_ordencommerce TO sec_ordencommerce; le cambié el nombre porque aunque no se ve hay unos caracteres escondidos debido a que estaban presentes en el archivo csv cuando copie los nombres de las columnas

select * from mae_ordenes where sec_ordencommerce like '18796400';﻿