-- CREATE SCHEMA IF NOT EXISTS   DOMO;

-- USE DOMO;

-- drop table mae_ordenes;

-- 2182 lineas/s

-- Después de todas las pruebas este ya queda

CREATE TABLE IF NOT EXISTS mae_ordenes(
sec_ordencommerce VARCHAR(20),
sec_orden VARCHAR(20),
fec_fechaorden DATETIME,
sec_nota VARCHAR(20),
sec_factura VARCHAR(20),
idu_clientecodigo VARCHAR(20),
nom_cliente VARCHAR(50),
nom_apellidopaterno VARCHAR(50),
nom_apellidomaterno VARCHAR(50),
des_correoelectronico VARCHAR(100),
num_telefono VARCHAR(20),
opc_celular VARCHAR(20),
nom_completorecibe VARCHAR(100),
idu_estadocodigo VARCHAR(20),
idu_MapaDomoCodigo VARCHAR(20),
nom_estado VARCHAR(50),
idu_ciudadcodigo VARCHAR(20),
nom_ciudad VARCHAR(50),
idu_coloniacodigo VARCHAR(20),
nom_colonia VARCHAR(50),
nom_calle VARCHAR(100),
nom_entrecalles VARCHAR(200),
num_casa VARCHAR(20),
num_interior VARCHAR(100),
num_exterior VARCHAR(20),
num_codigopostal VARCHAR(20),
des_observaciones VARCHAR(500),
idu_articulocodigo VARCHAR(20),
num_cantidad INT,
imp_preciounitario NUMERIC(8,2),
imp_preciocreditounitario  NUMERIC(8,2),
idu_articuloproductocommercecodigo VARCHAR(20),
idu_articuloitemcommercecodigo VARCHAR(20),
idu_tipopagocodigo VARCHAR(20),
des_tipopago VARCHAR(100),
des_tipocompra VARCHAR(100),
des_pagoinicial VARCHAR(100),
des_formapago VARCHAR(100),
des_tipopagogrupo VARCHAR(100),
des_tipopagogrupo2 VARCHAR(100),
des_tipopagogrupo3 VARCHAR(100),
idu_estatuspedidocodigo VARCHAR(20),
des_estatusorden VARCHAR(100),
idu_codigobanco VARCHAR(20),
des_establecimientobanco VARCHAR(100),
num_referencia VARCHAR(100),
fec_FechaFacturacion DATETIME,
idu_areacodigo VARCHAR(20),
des_Area VARCHAR(100),
idu_departamentocodigo VARCHAR(20),
des_departamento VARCHAR(100),
idu_clasecodigo VARCHAR(20),
des_clase VARCHAR(100),
idu_familiacodigo VARCHAR(20),
des_familia VARCHAR(100),
des_categoria VARCHAR(100),
des_subcategoria VARCHAR(100),
des_clasificacionantad VARCHAR(100),
des_articulo VARCHAR(100),
num_talla VARCHAR(50),
des_modelo VARCHAR(100),
des_color VARCHAR(100),
des_marca VARCHAR(100),
des_EstatusAccertify VARCHAR(100),
fec_fechaordencommerce DATETIME,
des_BuildingBlock VARCHAR(100),
des_buildingblockagg VARCHAR(100),
des_Fuente VARCHAR(100),
des_Medio VARCHAR(100),
des_campagna VARCHAR(200),
des_Dispositivo VARCHAR(100),
idu_TiendaCodigoR VARCHAR(20),
nom_NombreTiendaR VARCHAR(100),
idu_FormatoTiendaCodigoR VARCHAR(20),
des_FormatoTiendaR VARCHAR(100),
idu_CiudadTiendaCodigoR VARCHAR(20),
nom_NombreCiudadR VARCHAR(100),
flag_ventafuturo VARCHAR(20),
num_tiendaCT VARCHAR(20),
des_FormatoCT VARCHAR(100),
flag_logeado VARCHAR(20)
) ENGINE InnoDB;

-- 4) cargar los datos
LOAD DATA INFILE '/var/lib/mysql-files/mae_ordenes.csv'
into table mae_ordenes
FIELDS TERMINATED BY '|'
enclosed by '"'
LINES terminated by '\n'
IGNORE 1 ROWS

(@sec_ordencommerce,
@sec_orden,
@fec_fechaorden,
@sec_nota,
@sec_factura,
@idu_clientecodigo,
@nom_cliente,
@nom_apellidopaterno,
@nom_apellidomaterno,
@des_correoelectronico,
@num_telefono,
@opc_celular,
@nom_completorecibe,
@idu_estadocodigo,
@idu_MapaDomoCodigo,
@nom_estado,
@idu_ciudadcodigo,
@nom_ciudad,
@idu_coloniacodigo,
@nom_colonia,
@nom_calle,
@nom_entrecalles,
@num_casa,
@num_interior,
@num_exterior,
@num_codigopostal,
@des_observaciones,
@idu_articulocodigo,
@num_cantidad,
@imp_preciounitario,
@imp_preciocreditounitario,
@idu_articuloproductocommercecodigo,
@idu_articuloitemcommercecodigo,
@idu_tipopagocodigo,
@des_tipopago,
@des_tipocompra,
@des_pagoinicial,
@des_formapago,
@des_tipopagogrupo,
@des_tipopagogrupo2,
@des_tipopagogrupo3,
@idu_estatuspedidocodigo,
@des_estatusorden,
@idu_codigobanco,
@des_establecimientobanco,
@num_referencia,
@fec_FechaFacturacion,
@idu_areacodigo,
@des_Area,
@idu_departamentocodigo,
@des_departamento,
@idu_clasecodigo,
@des_clase,
@idu_familiacodigo,
@des_familia,
@des_categoria,
@des_subcategoria,
@des_clasificacionantad,
@des_articulo,
@num_talla,
@des_modelo,
@des_color,
@des_marca,
@des_EstatusAccertify,
@fec_fechaordencommerce,
@des_BuildingBlock,
@des_buildingblockagg,
@des_Fuente,
@des_Medio,
@des_campagna,
@des_Dispositivo,
@idu_TiendaCodigoR,
@nom_NombreTiendaR,
@idu_FormatoTiendaCodigoR,
@des_FormatoTiendaR,
@idu_CiudadTiendaCodigoR,
@nom_NombreCiudadR,
@flag_ventafuturo,
@num_tiendaCT,
@des_FormatoCT,
@flag_logeado)

SET

sec_ordencommerce= NULLIF(TRIM(@sec_ordencommerce),""),
sec_orden= NULLIF(TRIM(@sec_orden),""),
sec_nota= NULLIF(TRIM(@sec_nota),""),
sec_factura= NULLIF(TRIM(@sec_factura),""),
fec_fechaorden= NULLIF(TRIM(@fec_fechaorden),""),
idu_clientecodigo= NULLIF(TRIM(@idu_clientecodigo),""),
nom_cliente= NULLIF(TRIM(@nom_cliente),""),
nom_apellidopaterno= NULLIF(TRIM(@nom_apellidopaterno),""),
nom_apellidomaterno= NULLIF(TRIM(@nom_apellidomaterno),""),
des_correoelectronico= NULLIF(TRIM(@des_correoelectronico),""),
num_telefono= NULLIF(TRIM(@num_telefono),""),
opc_celular= NULLIF(TRIM(@opc_celular),""),
nom_completorecibe= NULLIF(TRIM(@nom_completorecibe),""),
idu_estadocodigo= NULLIF(TRIM(@idu_estadocodigo),""),
idu_MapaDomoCodigo= NULLIF(TRIM(@idu_MapaDomoCodigo),""),
nom_estado= NULLIF(TRIM(@nom_estado),""),
idu_ciudadcodigo= NULLIF(TRIM(@idu_ciudadcodigo),""),
nom_ciudad= NULLIF(TRIM(@nom_ciudad),""),
idu_coloniacodigo= NULLIF(TRIM(@idu_coloniacodigo),""),
nom_colonia= NULLIF(TRIM(@nom_colonia),""),
nom_calle= NULLIF(TRIM(@nom_calle),""),
nom_entrecalles= NULLIF(TRIM(@nom_entrecalles),""),
num_casa= NULLIF(TRIM(@num_casa),""),
num_interior= NULLIF(TRIM(@num_interior),""),
num_exterior= NULLIF(TRIM(@num_exterior),""),
num_codigopostal= NULLIF(TRIM(@num_codigopostal),""),
des_observaciones= NULLIF(TRIM(@des_observaciones),""),
idu_articulocodigo= NULLIF(TRIM(@idu_articulocodigo),""),
num_cantidad= NULLIF(TRIM(@num_cantidad),""),
imp_preciounitario= NULLIF(TRIM(@imp_preciounitario),""),
imp_preciocreditounitario= NULLIF(TRIM(@imp_preciocreditounitario),""),
idu_articuloproductocommercecodigo= NULLIF(TRIM(@idu_articuloproductocommercecodigo),""),
idu_articuloitemcommercecodigo= NULLIF(TRIM(@idu_articuloitemcommercecodigo),""),
idu_tipopagocodigo= NULLIF(TRIM(@idu_tipopagocodigo),""),
des_tipopago= NULLIF(TRIM(@des_tipopago),""),
des_tipocompra= NULLIF(TRIM(@des_tipocompra),""),
des_pagoinicial= NULLIF(TRIM(@des_pagoinicial),""),
des_formapago= NULLIF(TRIM(@des_formapago),""),
des_tipopagogrupo= NULLIF(TRIM(@des_tipopagogrupo),""),
des_tipopagogrupo2= NULLIF(TRIM(@des_tipopagogrupo2),""),
des_tipopagogrupo3= NULLIF(TRIM(@des_tipopagogrupo3),""),
idu_estatuspedidocodigo= NULLIF(TRIM(@idu_estatuspedidocodigo),""),
des_estatusorden= NULLIF(TRIM(@des_estatusorden),""),
idu_codigobanco= NULLIF(TRIM(@idu_codigobanco),""),
des_establecimientobanco= NULLIF(TRIM(@des_establecimientobanco),""),
num_referencia= NULLIF(TRIM(@num_referencia),""),
fec_FechaFacturacion= NULLIF(TRIM(@fec_FechaFacturacion),""),
idu_areacodigo= NULLIF(TRIM(@idu_areacodigo),""),
des_Area= NULLIF(TRIM(@des_Area),""),
idu_departamentocodigo= NULLIF(TRIM(@idu_departamentocodigo),""),
des_departamento= NULLIF(TRIM(@des_departamento),""),
idu_clasecodigo= NULLIF(TRIM(@idu_clasecodigo),""),
des_clase= NULLIF(TRIM(@des_clase),""),
idu_familiacodigo= NULLIF(TRIM(@idu_familiacodigo),""),
des_familia= NULLIF(TRIM(@des_familia),""),
des_categoria= NULLIF(TRIM(@des_categoria),""),
des_subcategoria= NULLIF(TRIM(@des_subcategoria),""),
des_clasificacionantad= NULLIF(TRIM(@des_clasificacionantad),""),
des_articulo= NULLIF(TRIM(@des_articulo),""),
num_talla= NULLIF(TRIM(@num_talla),""),
des_modelo= NULLIF(TRIM(@des_modelo),""),
des_color= NULLIF(TRIM(@des_color),""),
des_marca= NULLIF(TRIM(@des_marca),""),
des_EstatusAccertify= NULLIF(TRIM(@des_EstatusAccertify),""),
fec_fechaordencommerce= NULLIF(TRIM(@fec_fechaordencommerce),""),
des_BuildingBlock= NULLIF(TRIM(@des_BuildingBlock),""),
des_buildingblockagg= NULLIF(TRIM(@des_buildingblockagg),""),
des_Fuente= NULLIF(TRIM(@des_Fuente),""),
des_Medio= NULLIF(TRIM(@des_Medio),""),
des_campagna= NULLIF(TRIM(@des_campagna),""),
des_Dispositivo= NULLIF(TRIM(@des_Dispositivo),""),
idu_TiendaCodigoR= NULLIF(TRIM(@idu_TiendaCodigoR),""),
nom_NombreTiendaR= NULLIF(TRIM(@nom_NombreTiendaR),""),
idu_FormatoTiendaCodigoR= NULLIF(TRIM(@idu_FormatoTiendaCodigoR),""),
des_FormatoTiendaR= NULLIF(TRIM(@des_FormatoTiendaR),""),
idu_CiudadTiendaCodigoR= NULLIF(TRIM(@idu_CiudadTiendaCodigoR),""),
nom_NombreCiudadR= NULLIF(TRIM(@nom_NombreCiudadR),""),
flag_ventafuturo= NULLIF(TRIM(@flag_ventafuturo),""),
num_tiendaCT= NULLIF(TRIM(@num_tiendaCT),""),
des_FormatoCT= NULLIF(TRIM(@des_FormatoCT),""),
flag_logeado= NULLIF(TRIM(@flag_logeado),"");

-- select  * from mae_ordenes LIMIT 10;
