CREATE DATABASE COPPEL;

USE COPPEL;

-- Creo la tabla para guardar el archivo que me pasó Jaime
CREATE TABLE MOV_EXISTENCIAS_20200430(
des_Area VARCHAR(30),
des_Categoria VARCHAR(30),
idu_DepartamentoCodigo INTEGER,
des_Departamento VARCHAR(30),
idu_ClaseCodigo INTEGER,
des_Clase VARCHAR(30),
idu_FamiliaCodigo INTEGER,
des_Familia VARCHAR(30),
idu_ArticuloCodigo INTEGER,
num_Talla INTEGER,
imp_PrecioVenta INTEGER,
imp_PrecioPromocion INTEGER,
num_existencia INTEGER
);


-- 4) cargar los datos
LOAD DATA INFILE 'mov_existencias20200430.csv'
into table MOV_EXISTENCIAS_20200430
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES terminated by '\n'
IGNORE 1 ROWS;

-- SE CARGÓ EL ARCHIVO mov_existencias20200430.csv

select * from MOV_EXISTENCIAS_20200430;
-- --------------------------------------------------
-- Siguiente  tabla
-- GUARDO TODOS LOS REGISTROS CORRESPONDIENTES
-- A ZAPATOS Y LOS AGRUPO EN NUM_TALLA, SUMANDO LAS UNIDADES QUE TIENE CADA TALLA
CREATE TABLE CODIGOARTICULO_TALLAS_20200430 AS
SELECT
des_Area,
idu_DepartamentoCodigo,
des_Departamento,
idu_ClaseCodigo,
des_Clase,
idu_FamiliaCodigo,
des_Familia,
idu_ArticuloCodigo,
num_Talla, 
PRECIO(MAX(imp_PrecioVenta),
MAX(imp_PrecioPromocion)) AS IMPORTE_POR_UNIDAD, -- Este sería el importe invididual POR TALLA
SUM(num_existencia) AS UNIDADES -- Estas serían el total de unidades que existe POR TALLA
FROM MOV_EXISTENCIAS_20200430
WHERE des_Area="Zapatos"
GROUP BY des_Area, idu_DepartamentoCodigo,des_Departamento,idu_ClaseCodigo,des_Clase,idu_FamiliaCodigo,des_Familia,idu_ArticuloCodigo,num_Talla
ORDER BY idu_ArticuloCodigo desc, num_Talla desc;

select  * from CODIGOARTICULO_TALLAS_20200430;
 drop table CODIGOARTICULO_TALLAS_20200430;
 
-- NOTA
-- COMPROBÉ QUE LOS RESULTADOS FUERAN CORRECTOS
-- TOMANDO UN NUMERO DE ARTICULO AL AZAR Y HACIENDO EL CALCULO A MANO,
-- LO REPETÍ VARIAS VECES

-- ------------------------------------------------
-- Siguiente tabla
-- SE TOMAN SÓlO LOS  CODIGOS DE ARTICULO EN LOS CUALES LAS TALLAS TENGAN MENOS DE 3 UNIDADES
-- Y SE SUMA EL NÚMERO DE UNIDADES DE CADA TALLA
CREATE TABLE CODIGO_ARTICULO_E_IMPORTE_TOTAL_20200430 AS
SELECT
des_Area,
idu_DepartamentoCodigo,
des_Departamento,
idu_ClaseCodigo,
des_Clase,
idu_FamiliaCodigo,
des_Familia,
idu_ArticuloCodigo,
SUM(UNIDADES) AS UNIDADES_TOTALES, -- SERIA EL NUMERO TOTAL DE UNIDADES POR CÓDIGO DE ARTICULO
SUM(IMPORTE_POR_UNIDAD*UNIDADES) AS IMPORTE_TOTAL -- SERÍA EL IMPORTE TOTAL POR POR CÓDIGO DE ARTICULO
FROM CODIGOARTICULO_TALLAS_20200430
GROUP BY des_Area, idu_DepartamentoCodigo,des_Departamento,idu_ClaseCodigo,des_Clase,idu_FamiliaCodigo,des_Familia,idu_ArticuloCodigo
HAVING MAX(UNIDADES)<3 -- AQUI SE DESCARTAN LOS CODIGOS DE ARTICULOS QUE TENGAN 3 O MÁS UNIDADES EN ALGUNA DE SUS TALLAS, NOTESE QUE "UNIDADES" ES EL NUMERO DE UNIDADES POR TALLA NO POR ARTICULO
ORDER BY idu_ArticuloCodigo DESC;

drop table CODIGO_ARTICULO_E_IMPORTE_TOTAL_20200430;
select  * from CODIGO_ARTICULO_E_IMPORTE_TOTAL_20200430;

-- NOTA
-- COMPROBÉ QUE LOS RESULTADOS FUERAN CORRECTOS
-- TOMANDO UN NUMERO DE ARTICULO AL AZAR Y HACIENDO EL CALCULO A MANO,
-- LO REPETÍ VARIAS VECES

-- -----------------------------------------------------------
-- SIGUIENTE TABLA
-- AQUI SE OBTIENE EL NUMERO TOTAL DE UNIDADES POR CLASE-FAMILIA
CREATE TABLE UNIDADES_IMPORTE_TOTALES_20200430 AS -- por CLASE-FAMILIA
SELECT
des_Area,
idu_DepartamentoCodigo,
des_Departamento,
idu_ClaseCodigo,
des_Clase,
idu_FamiliaCodigo,
des_Familia,
SUM(UNIDADES_TOTALES) AS UNIDADES_TOTALES_CLASE_FAMILIA, -- SUMA LAS UNIDADES DE CADA ARTICULO QUE PERTENECE A LA MISMA CLASE-FAMILIA
SUM(IMPORTE_TOTAL) AS IMPORTE_TOTALES_CLASE_FAMILIA -- SUMA LOS IMPORTES DE CADA ARTICULO QUE PERTENECE A LA MISMA CLASE-FAMILIA
FROM CODIGO_ARTICULO_E_IMPORTE_TOTAL_20200430
GROUP BY des_Area, idu_DepartamentoCodigo,des_Departamento,idu_ClaseCodigo,des_Clase,idu_FamiliaCodigo,des_Familia
ORDER BY UNIDADES_TOTALES_CLASE_FAMILIA DESC;

drop table UNIDADES_IMPORTE_TOTALES_20200430;
select  * from UNIDADES_IMPORTE_TOTALES_20200430;


-- NOTA
-- COMPROBÉ QUE LOS RESULTADOS FUERAN CORRECTOS
-- TOMANDO UN PAR CALSE-FAMILIA AL AZAR Y HACIENDO EL CALCULO A MANO,
-- LO REPETÍ VARIAS VECES



